### PR TITLE
Fix the description

### PR DESCRIPTION
**Pull request by adamaltman**

### CODE REVIEW

**Comment by slavcodev** [comment]
Lol, I misread the diff and merged it. @adamaltman can you elaborate whwhat is this PR about? `descriptio` ?

**Comment by edmandiesamonte** [comment]
Lol. Same here. I approved it too. 😅

**Comment by edmandiesamonte** [comment]
@slavcodev the answer might be lying in the branch name that we missed `demo-do-not-merge`. 😄

**Comment by slavcodev** [comment]
Nice :D I don't used to read the branch :) The PR title says it's fix though.

**Pull request merged**
