### PR TITLE
Replace custom rule with native `tags-alphabetical`

### PR DESCRIPTION
**Pull request by justnero**
## Summary

[`tags-alphabetical`](https://redocly.com/docs/cli/rules/tags-alphabetical/) ~~is case-sensitive, so some tags were reordered~~. Native rule improvement merged and released, rule replaced clearly, no ordering changes required.

## Checklist

- [x] Writing style
- [x] API design standards

### CODE REVIEW

**Review by ashkarpetin — DISMISSED** [review]

**Comment by adamaltman** [comment]
Perhaps you can make an improvement to this:

https://github.com/Redocly/redocly-cli/blob/main/packages/core/src/rules/common/tags-alphabetical.ts

To add an optional property: `ignoreCase` (default `false`).

**Comment by justnero** [comment]
An improvement PR for `redocly-cli` is at https://github.com/Redocly/redocly-cli/pull/1258

**Review by noon-dawg — DISMISSED** [review]
Looks good on the docs side

**Comment by adamaltman** [comment]
Hoping for a release of Redocly CLI today/tomorrow.

**Review by ashkarpetin — APPROVED** [review]

**Review by noon-dawg — APPROVED** [review]

**Review by adamaltman — APPROVED** [review]

**Pull request merged**
