### PR TITLE
Check SDK operation name to be unique

### PR DESCRIPTION
**Pull request by 2e3s**
By analogy https://github.com/Redocly/openapi-cli/blob/master/packages/core/src/rules/common/operation-operationId-unique.ts

### CODE REVIEW

**Comment by 2e3s** [comment]
`x-sdk-operation-name` should not be globally unique, its uniqueness depends on some root object name which I haven't found in API defs.

**Comment by slavcoclone** [comment]
> its uniqueness depends on some root object name which I haven't found in API defs.

I guess it's related to operation tag. @agualis can you confirm?

**Comment by agualis** [comment]
> > its uniqueness depends on some root object name which I haven't found in API defs.
> 
> I guess it depends on operation tag. @agualis can you confirm?

It should be unique at `"sdk resource level"` as one resource file cannot have two functions with the same name.

The [mapping](https://github.com/Rebilly/rebilly-sdk-generator/blob/bb9048c37b21b68af7d62b3517d9f5c7af73fecb/src/sdk-generation/customizations/customizations.js#L24) between `schema paths` and `resource files` is currently done in the generator project. We could discuss if it's convenient to move that mapping to our definitions. Until then, I had added [this test](https://github.com/Rebilly/rebilly-sdk-generator/blob/bb9048c37b21b68af7d62b3517d9f5c7af73fecb/test/unit/specs/sdk-generation/from-schema-to-sdk.spec.js#L589) to detect duplications as we cannot check that uniqueness in `api-definitions`.

**Comment by agualis** [comment]
> > its uniqueness depends on some root object name which I haven't found in API defs.
> 
> I guess it depends on operation tag. @agualis can you confirm?

Answered in slack.

**Comment by 2e3s** [comment]
This is impossible to do at the moment because it needs the mapping from other repositories.

**Pull request closed without merging**
