### PR TITLE
Use single entrypoint

### PR DESCRIPTION
**Pull request by VladimirBerdnik**
This PR will remove multiple openapi files in favor of single `openapi.yaml` entrypoint.
All current references already use single entrypoint after [recent PR](https://github.com/Rebilly/api-definitions/pull/691). This PR is a final step AKA cleanup

### CODE REVIEW

**Comment by VladimirBerdnik** [comment]
php please review

**Review by ashkarpetin — APPROVED** [review]

**Review by agualis — APPROVED** [review]

**Review by agualis — CHANGES_REQUESTED** [review]
This change will break the js-sdk-generator. We need to understand how to fix it to be compatible with this.

**Comment by VladimirBerdnik** [comment]
> This change will break the js-sdk-generator. We need to understand how to fix it to be compatible with this.

@agualis , could you please explain what exactly is broken?

**Review by agualis — APPROVED** [review]

**Comment by agualis** [comment]
> > This change will break the js-sdk-generator. We need to understand how to fix it to be compatible with this.
> 
> @agualis , could you please explain what exactly is broken?

I re-approved the PR as [this change](https://github.com/Rebilly/rebilly-js-sdk/pull/372/files) would be  enough to fix the generator for now.

**Pull request merged**
