### PR TITLE
Products in operations

### PR DESCRIPTION
**Pull request by VladimirBerdnik**
This PR will allow to include specific operations into products bundles.
With this feature we can remove `users.yaml`, `core.yaml`, `combined.yaml`, `reports.yaml` and `storefront.yaml` but still build  these bundles with the help of `x-products` property and the products bundler plugin

### CODE REVIEW

**Comment by VladimirBerdnik** [comment]
devs please review

**Review by 2e3s — APPROVED** [review]

**Comment by VladimirBerdnik** [comment]
devs please review

**Review by ashkarpetin — APPROVED** [review]

**Review by adamaltman — APPROVED** [review]
Overall, I think this should be changed. The x-products seems redundant to me. Also, I'm not clear on the complete list... is it Core, Full, Risk Management, Users, Payments, Billing? (With that being said, I don't think this is harmful and we need to make the switch sooner rather than later.)

**Comment by adamaltman** [comment]
You already have a conflict to resolve. 🎃

**Pull request merged**
