### PR TITLE
Revert "Add quote for change items/reactivate order"

### PR DESCRIPTION
**Pull request by lexerom**
Reverts Rebilly/api-definitions#1727

Due to frontend failing tests

### CODE REVIEW

**Review by ikram-patah — APPROVED** [review]

**Comment by ashkarpetin** [comment]
Why reverted?

**Comment by lexerom** [comment]
> Why reverted?

Frontend tests are broken. Will merge it once frontend PR is deployed.

**Comment by ikram-patah** [comment]
Test thats failing
https://github.com/Rebilly/rebilly/actions/runs/7827568913/job/21355647437?pr=3382

**Comment by ashkarpetin** [comment]
@lexerom please next time add that information to description

**Review by ashkarpetin — APPROVED** [review]

**Pull request merged**
