### PR TITLE
Add Payment Gateway Metadata API

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by slavarebilly** [comment]
@Rebilly/php please review

**Review by ashkarpetin — DISMISSED** [review]

**Review by iamdevice — DISMISSED** [review]

**Comment by slavarebilly** [comment]
@Rebilly/php please re-review

**Comment by slavarebilly** [comment]
@Rebilly/js please re-review

**Review by ashkarpetin — DISMISSED** [review]

**Comment by slavarebilly** [comment]
@Rebilly/php please review

**Review by justnero — DISMISSED** [review]

**Pull request merged**
