### PR TITLE
Add Adyen mapping

### PR DESCRIPTION
**Pull request by dara123**

### CODE REVIEW

**Review by ashkarpetin — DISMISSED** [review]

**Review by colinbird — DISMISSED** [review]
Capitalization is `Adyen` on their site

**Comment by dara123** [comment]
@adamaltman should the name be `AdYen` or `Adyen` ?

**Comment by adamaltman** [comment]
Adyen, not AdYen

**Comment by dara123** [comment]
I will rename it

**Review by ashkarpetin — APPROVED** [review]

**Review by slavcodev — APPROVED** [review]

**Pull request merged**
